language: ruby
rvm:
  - 2.4.0

script: ./.ci/travis.sh

sudo: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - gem update --system
  - gem install bundler

addons:
  apt:
    packages:
      - oracle-java8-set-default

cache:
  directories:
    - venv
    - vendor
