- name: Resume
  icon: fa-list-ul
  link: cv.html
- name: Google Scholar
  icon: fa-graduation-cap
  link: "https://scholar.google.com/citations?user=VdxLaDEAAAAJ"
- name: ORCID
  icon: fa-id-card-o
  link: "https://orcid.org/0000-0002-8442-856X"
- name: DBLP
  icon: fa-file-text-o
  link: "https://dblp.org/pid/143/3168"
- name: GitHub
  icon: fa-github
  link: "https://github.com/larsrh"
- name: Twitter
  icon: fa-twitter
  link: "https://twitter.com/larsr_h"
- name: Instagram
  icon: fa-instagram
  link: "https://instagram.com/larsr_h"
- name: Keybase
  icon: fa-lock
  link: "https://keybase.io/larsrh"
- name: Speaker Deck
  icon: fa-desktop
  link: "https://speakerdeck.com/larsrh"
